### ISSUE TITLE
Menu/Drawer não atualiza as informações da sessão de maneira dinâmica

### ISSUE THREAD

**Issue by fariasmarcos** [caldasluan/meau#33]
Para reproduzir o erro basta entrar com uma conta qualquer e, em seguida, sair (pelo botão "sair" da tela inicial). O drawer vai continuar com as informações do usuário.

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Menu/Drawer não atualiza as informações da sessão de maneira dinâmica](https://trello.com/c/qgipO6Yo/36-menu-drawer-n%C3%A3o-atualiza-as-informa%C3%A7%C3%B5es-da-sess%C3%A3o-de-maneira-din%C3%A2mica)

**Comment by fariasmarcos** [comment]
@caldasluan e @jvmunhoz, necessita confirmação, reproduzam os passos e se o bug ocorrer, adicionem o label "confirmado".

**Comment by caldasluan** [comment]
O bug realmente ocorre, ao iniciar a função de de logout devemos colocar os valores antigos lá.
