### ISSUE TITLE
Funções que não serão implementadas aparecem no Drawer

### ISSUE THREAD

**Issue by fariasmarcos** [caldasluan/meau#35]
Refinar o menu retirando todas as opções que não serão implementadas.

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Funções que não serão implementadas aparecem no Drawer](https://trello.com/c/o9OIVJx1/38-fun%C3%A7%C3%B5es-que-n%C3%A3o-ser%C3%A3o-implementadas-aparecem-no-drawer)

**Comment by jvmunhoz** [comment]
Concordo, não há necessidade de mantê-las.
