### ISSUE TITLE
Feature implementada em #32 não está funcional

### ISSUE THREAD

**Issue by fariasmarcos** [caldasluan/meau#37]
As notificações de interesse e confirmação de adoção não são enviadas/recebidas como esperado.

**Comment by fariasmarcos** [comment]
Para mais detalhes, ver #32.

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature implementada em #32 não está funcional](https://trello.com/c/wYZmJBF8/39-feature-implementada-em-32-n%C3%A3o-est%C3%A1-funcional)

**Comment by caldasluan** [comment]
Vou começar a resolver este bug agora mesmo.
