### ISSUE TITLE
Login pela conta Google não funciona

### ISSUE THREAD

**Issue by fariasmarcos** [caldasluan/meau#38]
O aplicativo chega a chamar o overlay da Google para escolher uma conta, mas após a escolha nada acontece.

**Comment by fariasmarcos** [comment]
@caldasluan e @jvmunhoz, essa issue precisa de confirmação, tentem logar outra conta do Google ou deletem as de vocês lá no banco e refaçam o login. Se um dos dois confirmar o problema, adicionem o label "confirmado" para começarmos a investigar.

**Comment by caldasluan** [comment]
@fariasmarcos você conectou seu Android Studio ao Firebase? Senão ele não consegue gerar um apk pra debug com autorização ao Firebase.

**Comment by fariasmarcos** [comment]
@caldasluan eu consigo fazer o login e o cadastro. Esse processo de entrar no Firebase é específico para o login com o Google?

**Comment by fariasmarcos** [comment]
@caldasluan sua recomendação funcionou. Fechando a issue.
