### ISSUE TITLE
Fragments da MainActivity não entram na stack

### ISSUE THREAD

**Issue by fariasmarcos** [caldasluan/meau#41]
Com o usuário na MainActivity, o comportamento do botão voltar **deveria** ser alternar entre os fragments já abertos, porém o que vemos é a MainActivity ser fechada e o app retorna para a tela (Activity) inicial. É possível realizar essa correção sem alterar significativamente a estrutura da Activity?

**Comment by fariasmarcos** [comment]
@caldasluan tentei inserir `.addToBackStack(null)` nos `FragmentTransaction`, mas não obtive sucesso e o comportamento se manteve. Alguma sugestão?

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fragments da MainActivity não entram na stack](https://trello.com/c/aNbSwX5X/41-fragments-da-mainactivity-n%C3%A3o-entram-na-stack)

**Comment by caldasluan** [comment]
É provável que tenhamos que mudar a estrutura de como os Fragments são chamados, ou criarmos um pilha nós mesmos.
