### ISSUE TITLE
Notificações não funcionam no Samsung Galaxy S10

### ISSUE THREAD

**Issue by jvmunhoz** [caldasluan/meau#45]
Possui One Ui 1.1 no SDK 28 (Android 9). Entretanto, parecem funcionar em um Android 9 puro.

**Comment by jvmunhoz** [comment]
@caldasluan testa no seu celular que também é Samsung para ver se funciona

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notificações não funcionam no Samsung Galaxy S10](https://trello.com/c/wtJ2eSIS/44-notifica%C3%A7%C3%B5es-n%C3%A3o-funcionam-no-samsung-galaxy-s10)

**Comment by fariasmarcos** [comment]
@jvmunhoz issue resolvida pela Pull Request #59.
