### ISSUE TITLE
Implementar tela "Pets do meu interesse"

### ISSUE THREAD

**Issue by fariasmarcos** [caldasluan/meau#55]
Seria uma tela no mesmo esquema da tela "Adotar" e "Meus Pets", porém estariam listados os animais em que o usuário manifestou interesse. Ao tocar em um animal o programa deve abrir uma janela que indaga se o usuário deseja cancelar esse interesse. Uma forma de contornar essa tela seria proibindo o usuário de se interessar por mais de um animal ao mesmo tempo. De ambos os modos, deveria *também* existir uma maneira de cancelar o interesse em um animal.

**Comment by jvmunhoz** [comment]
Ideia interessante, entretanto teremos que ver quanto tempo teremos para implementá-la

**Comment by fariasmarcos** [comment]
Marcando como ignorado/inválido. Não cabe no projeto atual.
