### ISSUE TITLE
Adicionar mensagem para listas vazias

### ISSUE THREAD

**Issue by caldasluan** [caldasluan/meau#58]
Mostrar uma mensagem de erro dizendo que a lista está vazia, por exemplo, no caso do usuário não possuir nenhum pet.

**Comment by fariasmarcos** [comment]
Queria botar isso há anos, mas nunca achei que vocês iam ligar :D

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar mensagem para listas vazias](https://trello.com/c/8iJvVMQy/50-adicionar-mensagem-para-listas-vazias)

**Comment by fariasmarcos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar mensagem para listas vazias](https://trello.com/c/n5x6LAxD/51-adicionar-mensagem-para-listas-vazias)
